### ISSUE TITLE
Tests for inputs do not include closing tag

### ISSUE THREAD

**Issue by DerekKaknes** [learn-co-curriculum/sinatra-restful-routes-lab#13]
The tests for this lesson look for an input tag without a proper closing tag, eg. `include("<input>")` instead of `include("<input/>")`.  This can become problematic when using Capybara to test form submission, so these tests should not be reinforcing it.

**Comment by aturkewi** [comment]
Googling around about this, it seems like ending `/>` is proper when using HTML5, but not a great idea when using earlier versions like HTML4. So the _best_ option to use would depend on which doc type is declared. It looks like we're not actually declaring one or the other for simplicity sake, so I'm inclined to just leave it as is. 

I'm going to close this issue out for now, but please feel free to re-open it with more information or if you are seeing this actually cause problems with the lab :)
