### ISSUE TITLE
Rspec issue

### ISSUE THREAD

**Issue by dslivken** [learn-co-curriculum/sinatra-restful-routes-lab#14]
I could not get the "redirects to the recipe show page" test to pass (line 120) even though everything seemed correct.  I kept getting this error:

  1) Recipe App creating a new recipe redirects to the recipe show page                  
     Failure/Error: expect(last_request.url).to include("/recipes/#{Recipe.last.id}")    
       expected "http://example.org/recipes" to include "/recipes/3" 

"http://example.org/recipes" seemed to be the problem, so I changed line 121 in the test file to this: 
from "expect(last_request.url…"
to "expect(last_response.body…"

Can someone please advise?

**Comment by itzsaga** [comment]
Were you using `'` or `"` around your redirect? String interpolation won't happen with `'`

**Comment by aturkewi** [comment]
This is more of a question for Ask A Question than an issue with the lab. Looking at the error message posted, it looks like redirects are going to `/recipes` and not `recipes/:id`. I would try this running in your browser first and make sure you're seeing what you expect and then go back to the tests. If you still need a hand, I think Ask A Question or the slack channel would be the best place to go :)
