### ISSUE TITLE
Students need to write: use Rack::MethodOverride   in config.ru file

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/sinatra-restful-routes-lab#23]
This should be either provided in the master code or clearly referenced in the readme as this is a very obscure thing that most of us tech coaches do not even remember. It is needed so that Sinatra can handle patch and delete methods.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @justinddaniel.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
