### ISSUE TITLE
The Pry gem needs to be moved outside of the "test" group in the Gemfile

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/sinatra-restful-routes-lab#27]
Hi. I tried to use `rake console` when I wanted to test out my database. However, I got an error because of an "uninitialized constant Pry". 

It turns out that the the Pry gem in the Gemfile is only inside of the "test" environment, but the Rakefile (where `rake console` is defined) uses the "development" environment. Because of that, I can't use `rake console` from the terminal.

Instead of putting `gem 'pry'` inside of the "test" group in the Gemfile, put it with the other ("default" environment) gems above it.

Thanks as always for looking into this!

---Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
