### ISSUE TITLE
Possible typo in the spec tests

### ISSUE THREAD

**Issue by wyao905** [learn-co-curriculum/sinatra-restful-routes-lab#28]
The test set "creating a new recipe" seems to have a typo on line 127.  The code shows the following:

```ruby
describe "creating a new recipe" do 
    before do 
      params = {
        "name" => "pumpkin pie",
        "ingredients" => "pumpkin, flour, butter, sugar",
        "cook_time" => "1 hour"
      }
      post '/recipes', params
      follow_redirect!
    end
```

Believe that `post'/recipes', params` should be `post '/recipes/new', params`. I've changed line 127 in the tests and moved on with the lab.

**Comment by sgharms** [comment]
I don't believe that you are correct here.

`/recipes/new` should be a GET action that renders a form that takes data
`/recipes/` should be a POST action that receives params and then uses them to update the database and then redirects to the `/recipes/:recipe_id` handler.

You might want to engage a coach in this.
